name: Docker Image CI/CD

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # API Docker Image
      - name: Login to Docker Hub (API)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (API)
        run: docker build ./api/ -t thaboxanx/devops_api:v1

      - name: Push to Docker Hub (API)
        run: docker push thaboxanx/devops_api:v1

      # Frontend Docker Image
      - name: Login to Docker Hub (Frontend)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (Frontend)
        run: docker build ./front-end-nextjs/ -t thaboxanx/devops_frontend:v1

      - name: Push to Docker Hub (Frontend)
        run: docker push thaboxanx/devops_frontend:v1
