name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Images
        run: |
          docker build ./api/ -t thaboxanx/devops_api:v1 -t thaboxanx/devops_api:latest
          docker build ./front-end-nextjs/ -t thaboxanx/devops_frontend:v1 -t thaboxanx/devops_frontend:latest

      - name: Push Images to Docker Hub
        run: |
          docker push thaboxanx/devops_api:v1
          docker push thaboxanx/devops_api:latest
          docker push thaboxanx/devops_frontend:v1
          docker push thaboxanx/devops_frontend:latest
