name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.thaboxanx }} -p ${{ secrets.dckr_pat_3iK7C5whwLIdp2pTYj6QTMT1Jfs }}

      - name: Build image
        run: docker build ./api/ -t thaboxanx/devops_api:v1

      - name: Push to Docker Hub
        run: docker push thaboxanx/devops_api:v1
